### ISSUE TITLE
I made an icon for this mod if you want to use it!

### ISSUE THREAD

**Issue by RueOfficial** [ZiLko/Better_Screenshots#2]
![Icon Template - S1](https://github.com/ZiLko/Better_Screenshots/assets/60704088/2530139b-6812-4b3e-a87d-ce3a08575ca9)
I wanted to make the icon match the others and also add more detail to the camera too and increase the resolution, you are free to use it, no need to credit but you can if you want to

**Comment by RueOfficial** [comment]
![image](https://github.com/ZiLko/Better_Screenshots/assets/60704088/ecf7764f-0f47-406b-8a02-23fcb083b4ea)
How it would look ingame, if you want to make any changes lmk

**Comment by Zilko** [comment]
wtf this is beautiful
will change it to this one and give you credits
